name: build image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      
permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  PLATFORMS: linux/arm/v7

jobs:
  build-image:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Retrieve image version
      run: echo "IMAGE_VERSION=$(head -1 Dockerfile | grep -oP '(?<=caddy:).*?(?=-builder)')" >> $GITHUB_ENV
    - name: Parse version ranges
      run: |
        echo "IMAGE_VERSION_MAJOR=$(echo $IMAGE_VERSION | cut -d '.' -f 1)" >> $GITHUB_ENV
        echo "IMAGE_VERSION_MAJOR_MINOR=$(echo $IMAGE_VERSION | cut -d '.' -f 1,2)" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        platforms: ${{ env.PLATFORMS }}
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
          ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION_MAJOR }}
          ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION_MAJOR_MINOR }}
          ${{ env.IMAGE_NAME }}:latest
